name: Run npm test

on:
  push:
    branches:
      - main  # Replace with your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'  # Use the Node.js version you're working with

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'  # Use the Node.js version you're working with
    
    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        accountId: 55d61194f5027233eff9801665c070c7
        projectName: calculator-refactoring
        directory: dist
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        # Add other options here like project name, build command etc.